### ISSUE TITLE
Minor edits from EOM PIO

### ISSUE THREAD

**Issue by juliekdang** [DCgov/Community-Engagement-Program#15]
No. | Issue | Action
--- | --- | ---
1 | For the purposes of this administration DC Government includes the capital G (AP style uses of lowercase g)  | change all occurrences of "DC government" to "DC Government"
2 | On the section about SpeakUp on Housing... we should also hyperlink to the DMPED site – dmped.dc.gov | they don't notice the hyperlink, so add underlines to hyperlink style
3 | Capitalize 'City' where appropriate | as requested
4 | Use singular voice where appropriate for DC Government | as requested

**Comment by unlockedSound** [comment]
updated
