### ISSUE TITLE
Make Newspaper title ambiguous

### ISSUE THREAD

**Issue by juliekdang** [DCgov/Community-Engagement-Program#16]
Request:
> On the Section entitled What is SpeakUp – the third graphic (from the left) would need to say Newspaper or Washington Newspaper or some other fictitious name.  Washington Post  is too close to The Washington Post. 

This was a part of a storyboard scrawled on paper with pen. My idea for how to fix digitally without creating a wonky frankengraphic:

1. write (legibly) "Newspaper" in black on paper
2. take photo of paper
3. apply high contrast
4. crop and size to fit over 'Washington Post'

**Comment by unlockedSound** [comment]
uploading new photo with next commit
