### ISSUE TITLE
Revised "What is it?" text

### ISSUE THREAD

**Issue by gankatie** [DCgov/Community-Engagement-Program#2]
![image](https://user-images.githubusercontent.com/25327089/41741592-8df0a806-7569-11e8-8a7d-b4b989ef6b78.png)
"This is a tool to promote conversations between people in DC. The conversations start with quick surveys and polls--gathering opinions from residents about their experiences and priorities. People in DC Government then use the data and the conversations it sparks to make decisions, communicate with residents, and drive change. Residents and community groups can also use the data to stay informed, understand how their feedback has influenced decisions and the city, and shape the city.

**Comment by juliekdang** [comment]
How about pulling the concrete description up front? I agree that "conversation" captures the experience of what we are creating quite nicely, but the concept may be somewhat fuzzy for lay person in this context. I propose:

> This is a tool to gather opinions from residents about their experiences and priorities. Its purpose is to spark "conversations" between government and residents, starting with a quick survey or poll. People in DC Government then use the results to make decisions, communicate with residents, and drive change. These results are shared transparently so that residents can see how their feedback has influenced decisions and the city.

**Comment by gankatie** [comment]
Works for me (but I'd take "conversations" out of quotation marks)!
