### ISSUE TITLE
Cartoon box 1 caption

### ISSUE THREAD

**Issue by gankatie** [DCgov/Community-Engagement-Program#3]
People in DC Government are confronted by an important decision that should be informed by residents' voices, experiences, and perceptions. We quickly survey a representative group of residents, in ways that residents want (phones, online, mailboxes, in person....).

**Comment by unlockedSound** [comment]
effectively undoes a text change we made to make the boxes behave. 

The result of making the change in the issue is attached below.

![image](https://user-images.githubusercontent.com/18224436/41937235-c9b98478-795d-11e8-8bfd-38516da9097e.png)

**Comment by gankatie** [comment]
Text on box 1 is super long - what if we used the following illustration for the first sentence? 
![image](https://user-images.githubusercontent.com/25327089/41937846-6bf96dc4-795f-11e8-8f34-9ec36d8ab6ef.png)

**Comment by gankatie** [comment]
(but without the number). Text in the bubbles is "What do people want here?" "What should we do about this?" and "What's happening here?"

**Comment by juliekdang** [comment]
I agree this is part of the story, but the resident focus and clarity in the first slide make it a good option. Can we solve the problem by reducing the text of the first slide and including the gist of the proposed slide?

How about this?
> Government decision makers want public input on a policy or plan, so they do a quick, easy survey of a representative group of residents online, by phone, mail, kiosk, etc.

**Comment by gankatie** [comment]
Works for me!

Sent from my iPhone

On Jun 26, 2018, at 5:04 PM, Julie K <notifications@github.com<mailto:notifications@github.com>> wrote:


I agree this is part of the story, but the resident focus and clarity in the first slide make it a good option. Can we solve the problem by reducing the text of the first slide and including the gist of the proposed slide?

How about this?

Government decision makers want public input on a policy or plan, so they do a quick, easy survey of a representative group of residents online, by phone, mail, kiosk, etc.

**Comment by unlockedSound** [comment]
text changed and pushed
