### ISSUE TITLE
Cartoon box 2 caption

### ISSUE THREAD

**Issue by gankatie** [DCgov/Community-Engagement-Program#6]
![image](https://user-images.githubusercontent.com/25327089/41790671-48d95020-7621-11e8-9a59-5ab224e3c248.png)

I'm worried that we're prioritizing the fact that people aren't informed as the main barrier to engagement.

"Empowered with a convenient way engage, more residents give their feedback and opinions on issues taht matter to them."

**Comment by unlockedSound** [comment]
Empowered with relevant information, people provide feedback and give their opinions.

changed to 
Empowered with a convenient way to engage, more residents give their feedback and opinions on issues that matter to them.
